# Build and deploy Python app (Streamlit) to Azure Web App - opcr8-streamlit

name: Build and deploy Streamlit app to Azure Web App - opcr8-streamlit

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/main_opcr8-streamlit.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Créer l'environnement virtuel et installer les dépendances
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app-streamlit
          path: |
            .
            !antenv/
            !api/
            !models/
            !src/
            !notebooks/
            !.git/
            !venv/
            !mlruns/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app-streamlit

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'opcr8-streamlit'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0F49B09E96B1437CA454EAF86EC91474 }}
